"""测试 maw/runtimes/freezer.py（通用冻结器：声明驱动命令 + CPU 变体生成）。"""

from __future__ import annotations

import os
import shutil
import tempfile
import unittest
import unittest.mock
from pathlib import Path

from maw.runtimes import freezer as freezer_mod
from maw.runtimes.base import RuntimeSpec
from maw.runtimes.local_spec import LOCAL_SPEC
from maw.runtimes.ocr_spec import OCR_SPEC
from maw.runtimes.moss_spec import MOSS_SPEC

UV = Path("C:/tools/uv.exe")
BUILD = Path("repo/build")

MOSS_IN = """\
# MOSS 依赖声明（GPU 分支 pin cu130 本地版本）。
av>=14.0
torch==2.13.0+cu130; sys_platform != 'darwin'
torch>=2.13.0; sys_platform == 'darwin'
torchaudio==2.11.0+cu130; sys_platform != 'darwin'
torchaudio>=2.11.0; sys_platform == 'darwin'
safetensors>=0.6.2
"""

EXPORT_SAMPLE = """\
# This file was autogenerated by uv via the following command:
#    uv export --frozen --only-group local
accelerate==1.12.0 \\
    --hash=sha256:abc123
    # via
    #   moys-asr-workflow
    #   qwen-asr
gradio==6.17.3 \\
    --hash=sha256:def456
    # via qwen-asr
torch==2.13.0+cu130 ; sys_platform != 'darwin' \\
    --hash=sha256:eee789
    # via
    #   accelerate
    #   moys-asr-workflow
audioop-lts==0.2.2 ; python_full_version >= '3.13' \\
    --hash=sha256:fff000
    # via funasr
funasr==1.4.2 \\
    --hash=sha256:abc111
    # via moys-asr-workflow
"""


class StripGpuPinsTests(unittest.TestCase):
    def test_strips_local_version_suffix(self) -> None:
        self.assertEqual(
            freezer_mod.strip_gpu_pins("torch==2.13.0+cu130"),
            "torch==2.13.0",
        )

    def test_no_cu_pin_is_identity(self) -> None:
        line = "numba>=0.61.0"
        self.assertEqual(freezer_mod.strip_gpu_pins(line), line)


class CpuRequirementsLinesTests(unittest.TestCase):
    def test_moss_input_drops_darwin_branch_and_strips_marker_and_cu(self) -> None:
        lines = freezer_mod.cpu_requirements_lines(MOSS_IN)
        # 源注释不带入（头部注释由 cpu_input_text 负责），darwin 分支丢弃，
        # 剩余依赖行无 marker / 无 +cu
        self.assertNotIn("# MOSS 依赖声明（GPU 分支 pin cu130 本地版本）。", lines)
        self.assertEqual(lines, ["av>=14.0", "torch==2.13.0", "torchaudio==2.11.0", "safetensors>=0.6.2"])
        self.assertNotIn("sys_platform", "".join(lines))
        self.assertNotIn("+cu130", "".join(lines))
        self.assertNotIn("darwin", "".join(lines))

    def test_export_pin_lines_also_cpu_normalized(self) -> None:
        lines = freezer_mod.cpu_requirements_lines(
            "torch==2.13.0+cu130 ; sys_platform != 'darwin'\n"
            "torch==2.13.0 ; sys_platform == 'darwin'\n"
            "audioop-lts==0.2.2 ; python_full_version >= '3.13'\n"
        )
        # darwin 分支丢弃；!= darwin 条件剥离；无关 marker 保留
        self.assertEqual(lines, ["torch==2.13.0", "audioop-lts==0.2.2 ; python_full_version >= '3.13'"])

    def test_cpu_input_text_ends_with_lf_and_accepts_header(self) -> None:
        text = freezer_mod.cpu_input_text(MOSS_IN, header="# CPU 变体\n")
        self.assertTrue(text.endswith("\n"))
        self.assertTrue(text.startswith("# CPU 变体\n"))
        self.assertIn("torch==2.13.0\n", text)


class DirectPinsFromExportTests(unittest.TestCase):
    def test_extracts_direct_pins_only(self) -> None:
        pins = freezer_mod.direct_pins_from_export(EXPORT_SAMPLE)
        self.assertEqual(
            pins,
            [
                "accelerate==1.12.0",
                "torch==2.13.0+cu130 ; sys_platform != 'darwin'",
                "funasr==1.4.2",
            ],
        )

    def test_extracts_dependency_group_roots_without_via_annotations(self) -> None:
        export = """\
accelerate==1.12.0 \\
    --hash=sha256:abc123
funasr==1.4.2 \\
    --hash=sha256:def456
    # via accelerate
torch==2.13.0+cu130 ; sys_platform != 'darwin' \\
    --hash=sha256:eee789
    # via accelerate
"""
        self.assertEqual(
            freezer_mod.direct_pins_from_export(
                export,
                direct_names={"accelerate", "funasr", "torch"},
            ),
            [
                "accelerate==1.12.0",
                "funasr==1.4.2",
                "torch==2.13.0+cu130 ; sys_platform != 'darwin'",
            ],
        )

    def test_empty_input(self) -> None:
        self.assertEqual(freezer_mod.direct_pins_from_export(""), [])


class FreezeCommandTests(unittest.TestCase):
    def test_local_main_uses_uv_export(self) -> None:
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, LOCAL_SPEC, BUILD),
            [str(UV), "export", "--frozen", "--only-group", "local",
             "--format", "requirements-txt", "-o", str(BUILD / "requirements-local.txt")],
        )

    def test_ocr_main_uses_uv_export(self) -> None:
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, OCR_SPEC, BUILD),
            [str(UV), "export", "--frozen", "--only-group", "ocr",
             "--format", "requirements-txt", "-o", str(BUILD / "requirements-ocr.txt")],
        )

    def test_moss_main_compiles_in_file_with_cu130_index(self) -> None:
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, MOSS_SPEC, BUILD),
            [str(UV), "pip", "compile", "moss-requirements.in", "-p", "3.11",
             "--extra-index-url", "https://download.pytorch.org/whl/cu130",
             "--index-strategy", "unsafe-best-match",
             "-o", str(BUILD / "requirements-moss.txt")],
        )

    def test_cpu_variants_compile_generated_input_in_build_dir(self) -> None:
        for spec, name in ((LOCAL_SPEC, "local"), (MOSS_SPEC, "moss")):
            with self.subTest(spec=spec.key):
                self.assertEqual(
                    freezer_mod.cpu_freeze_command(UV, spec, BUILD),
                    [str(UV), "pip", "compile", str(BUILD / f"{name}-cpu-requirements.in"),
                     "-p", "3.11", "--generate-hashes",
                     "--index-strategy", "unsafe-best-match",
                     "-o", str(BUILD / f"requirements-{name}-cpu.txt")],
                )

    def test_ocr_has_no_cpu_variant(self) -> None:
        self.assertIsNone(freezer_mod.cpu_freeze_command(UV, OCR_SPEC, BUILD))


class EnsureFrozenTests(unittest.TestCase):
    def _temp_build_dir(self) -> Path:
        build = Path(tempfile.mkdtemp()) / "build"
        build.mkdir(parents=True)
        self.addCleanup(lambda: shutil.rmtree(build.parent, ignore_errors=True))
        return build

    def _fake_run(self, calls: list[list[str]]) -> object:
        def run(command: list[str]) -> object:
            calls.append(command)
            index = command.index("-o")
            Path(command[index + 1]).write_text(EXPORT_SAMPLE, encoding="utf-8")
            return 0

        return run

    def test_main_generated_when_missing_and_skipped_when_present(self) -> None:
        build = self._temp_build_dir()
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, LOCAL_SPEC, cpu=False, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(calls[0][1:3], ["export", "--frozen"])
        # 已存在则不再触发
        before = len(calls)
        freezer_mod.ensure_frozen(UV, LOCAL_SPEC, cpu=False, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(len(calls), before)

    def test_local_cpu_exports_main_first_then_compiles(self) -> None:
        build = self._temp_build_dir()
        calls: list[list[str]] = []
        emitted: list[str] = []
        freezer_mod.ensure_frozen(
            UV, LOCAL_SPEC, cpu=True, build_dir=build,
            run=self._fake_run(calls),
            emit=emitted.append,
        )
        # 先 export 主清单（提取直接依赖的源），再 compile CPU 变体
        self.assertEqual(calls[0][1:3], ["export", "--frozen"])
        self.assertEqual(calls[1][1:3], ["pip", "compile"])
        self.assertIn("--generate-hashes", calls[1])
        # 生成式 in 文件已落盘，且内容被 CPU 归一化（无 +cu130）
        cpu_in = build / "local-cpu-requirements.in"
        self.assertTrue(cpu_in.is_file())
        content = cpu_in.read_text(encoding="utf-8")
        self.assertIn("funasr==1.4.2", content)
        self.assertIn("torch==2.13.0", content)
        self.assertNotIn("+cu130", content)
        self.assertIn("正在生成", "".join(emitted))

    def test_local_cpu_reuses_existing_main_export(self) -> None:
        build = self._temp_build_dir()
        (build / "requirements-local.txt").write_text(EXPORT_SAMPLE, encoding="utf-8")
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, LOCAL_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))
        # 主清单已存在，只执行 compile
        self.assertEqual(len(calls), 1)
        self.assertEqual(calls[0][1:3], ["pip", "compile"])

    def test_moss_cpu_derives_input_from_in_file(self) -> None:
        build = self._temp_build_dir()
        in_path = build.parent / "moss-requirements.in"
        in_path.write_text(MOSS_IN, encoding="utf-8")
        calls: list[list[str]] = []

        with tempfile.TemporaryDirectory() as unrelated_cwd:
            old_cwd = Path.cwd()
            try:
                os.chdir(unrelated_cwd)
                freezer_mod.ensure_frozen(
                    UV, MOSS_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls)
                )
            finally:
                os.chdir(old_cwd)

        self.assertEqual(len(calls), 1)
        self.assertEqual(calls[0][1:3], ["pip", "compile"])
        self.assertNotIn("extra-index-url", calls[0])
        cpu_in = build / "moss-cpu-requirements.in"
        self.assertTrue(cpu_in.is_file())
        content = cpu_in.read_text(encoding="utf-8")
        self.assertIn("torch==2.13.0\n", content)
        self.assertNotIn("; sys_platform", content)

    def test_ocr_cpu_variant_never_runs(self) -> None:
        build = self._temp_build_dir()
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, OCR_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(calls, [])

    def test_existing_cpu_txt_skips_generation(self) -> None:
        build = self._temp_build_dir()
        (build / "requirements-moss-cpu.txt").write_text("torch==2.13.0\n", encoding="utf-8")
        calls: list[list[str]] = []
        freezer_mod.ensure_frozen(UV, MOSS_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))
        self.assertEqual(calls, [])

    def test_cpu_generation_creates_missing_build_dir(self) -> None:
        parent = Path(tempfile.mkdtemp())
        self.addCleanup(lambda: shutil.rmtree(parent, ignore_errors=True))
        build = parent / "build"
        (parent / "moss-requirements.in").write_text(MOSS_IN, encoding="utf-8")
        calls: list[list[str]] = []

        freezer_mod.ensure_frozen(UV, MOSS_SPEC, cpu=True, build_dir=build, run=self._fake_run(calls))

        self.assertTrue((build / "moss-cpu-requirements.in").is_file())
        self.assertTrue((build / "requirements-moss-cpu.txt").is_file())
        self.assertEqual(len(calls), 1)

    def test_force_regenerates_existing_main_and_cpu_outputs(self) -> None:
        build = self._temp_build_dir()
        (build / "requirements-moss.txt").write_text("old-main\n", encoding="utf-8")
        (build / "requirements-moss-cpu.txt").write_text("old-cpu\n", encoding="utf-8")
        (build.parent / "moss-requirements.in").write_text(MOSS_IN, encoding="utf-8")
        calls: list[list[str]] = []

        freezer_mod.ensure_frozen(
            UV, MOSS_SPEC, cpu=False, build_dir=build,
            run=self._fake_run(calls), force=True,
        )
        freezer_mod.ensure_frozen(
            UV, MOSS_SPEC, cpu=True, build_dir=build,
            run=self._fake_run(calls), force=True,
        )

        self.assertEqual(len(calls), 2)
        self.assertNotEqual((build / "requirements-moss.txt").read_text(encoding="utf-8"), "old-main\n")
        self.assertNotEqual((build / "requirements-moss-cpu.txt").read_text(encoding="utf-8"), "old-cpu\n")


class RequirementsStaleTests(unittest.TestCase):
    """清单覆盖度判定：build/ 产物落后于当前声明时必须强制重新冻结。"""

    def _temp_build_dir(self) -> Path:
        build = Path(tempfile.mkdtemp()) / "build"
        build.mkdir(parents=True)
        self.addCleanup(lambda: shutil.rmtree(build.parent, ignore_errors=True))
        return build

    def _write_group(self, build: Path, entries: str) -> None:
        (build.parent / "pyproject.toml").write_text(
            "[dependency-groups]\nlocal = [" + entries + "]\n", encoding="utf-8"
        )

    def test_declared_names_from_group_and_in_file(self) -> None:
        build = self._temp_build_dir()
        self._write_group(build, '"funasr==1.4.2", "Quapeaks>=2026.0.0"')
        self.assertEqual(
            freezer_mod.declared_direct_names(LOCAL_SPEC, build),
            {"funasr", "quapeaks"},
        )
        (build.parent / "moss-requirements.in").write_text(
            "# comment\n-r base.in\ntorch==2.13.0+cu130; sys_platform != 'darwin'\nav>=14.0\n",
            encoding="utf-8",
        )
        self.assertEqual(
            freezer_mod.declared_direct_names(MOSS_SPEC, build),
            {"torch", "av"},
        )

    def test_stale_when_main_missing_or_incomplete(self) -> None:
        build = self._temp_build_dir()
        self._write_group(build, '"funasr==1.4.2", "quapeaks>=2026.0.0"')
        # 主清单缺失
        self.assertTrue(freezer_mod.requirements_stale(LOCAL_SPEC, build, cpu=False))
        # 主清单缺新声明的依赖（runtime 7 案例）
        (build / "requirements-local.txt").write_text("funasr==1.4.2\n", encoding="utf-8")
        self.assertTrue(freezer_mod.requirements_stale(LOCAL_SPEC, build, cpu=False))
        # 覆盖完整（名字做 PEP 503 归一化对比，哈希续行不干扰）
        (build / "requirements-local.txt").write_text(
            "funasr==1.4.2 \\\n    --hash=sha256:abc\nQuapeaks==2026.6.0\n",
            encoding="utf-8",
        )
        self.assertFalse(freezer_mod.requirements_stale(LOCAL_SPEC, build, cpu=False))

    def test_stale_cpu_variant_only_counts_when_requested(self) -> None:
        build = self._temp_build_dir()
        self._write_group(build, '"funasr==1.4.2"')
        (build / "requirements-local.txt").write_text("funasr==1.4.2\n", encoding="utf-8")
        (build / "requirements-local-cpu.txt").write_text("funasr==1.4.2\n", encoding="utf-8")
        self.assertFalse(freezer_mod.requirements_stale(LOCAL_SPEC, build, cpu=False))
        # CPU 清单缺依赖：只在请求 CPU 变体时判过期
        (build / "requirements-local-cpu.txt").write_text("old-cpu==1.0\n", encoding="utf-8")
        self.assertFalse(freezer_mod.requirements_stale(LOCAL_SPEC, build, cpu=False))
        self.assertTrue(freezer_mod.requirements_stale(LOCAL_SPEC, build, cpu=True))

    def test_unverifiable_declaration_keeps_idempotent_skip(self) -> None:
        # 旧 extra 回退（无 in / 无 group）：无法判定时不强制，维持旧行为。
        build = self._temp_build_dir()
        spec = RuntimeSpec(
            key="x", runtime_version="1", python_version="3.11",
            embed_python_zip="", requirements_emit="", requirements_key="x",
            requirements_bundle_name="requirements-x.txt", verify_command="",
            package_dirs=(), worker_module="", message_prefix="", feature_label="",
            missing_detail="", ready_detail="", fix_action_label="",
            ready_emit_done="", dir_name="x", root_env="MAW_X_ROOT", bundle_dir="x",
        )
        self.assertEqual(freezer_mod.declared_direct_names(spec, build), set())
        self.assertFalse(freezer_mod.requirements_stale(spec, build, cpu=False))


class RuntimeSpecDefaultsTests(unittest.TestCase):
    def test_new_fields_default_to_export_recipe(self) -> None:
        spec = RuntimeSpec(
            key="x", runtime_version="1", python_version="3.11",
            embed_python_zip="", requirements_emit="", requirements_key="x",
            requirements_bundle_name="requirements-x.txt", verify_command="",
            package_dirs=(), worker_module="", message_prefix="", feature_label="",
            missing_detail="", ready_detail="", fix_action_label="",
            ready_emit_done="", dir_name="x", root_env="MAW_X_ROOT", bundle_dir="x",
        )
        self.assertIsNone(spec.requirements_in)
        self.assertIsNone(spec.requirements_group)
        self.assertEqual(spec.requirements_in_args, ())
        self.assertEqual(
            freezer_mod.main_freeze_command(UV, spec, BUILD)[1:3],
            ["export", "--frozen"],
        )


if __name__ == "__main__":
    unittest.main()
